apiVersion: v1
kind: Namespace
metadata:
  name:  mango-namespace


apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mango-namespace 
  name: my-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp
        image: nginx:alpine
        ports:
        - containerPort: 80

